/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"
/* Header for class com_cheuks_bin_anythingtest_jni_DllInterface */

#ifndef _Included_com_cheuks_bin_anythingtest_jni_DllInterface
#define _Included_com_cheuks_bin_anythingtest_jni_DllInterface
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_cheuks_bin_anythingtest_jni_DllInterface
 * Method:    FindWindowEx
 * Signature: (IILjava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cheuks_bin_anythingtest_jni_DllInterface_FindWindowEx
  (JNIEnv *, jobject, jint, jint, jstring, jstring);

/*
 * Class:     com_cheuks_bin_anythingtest_jni_DllInterface
 * Method:    FindWindow
 * Signature: (Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_com_cheuks_bin_anythingtest_jni_DllInterface_FindWindow
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_cheuks_bin_anythingtest_jni_DllInterface
 * Method:    SetWindowText
 * Signature: (ILjava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cheuks_bin_anythingtest_jni_DllInterface_SetWindowText
  (JNIEnv *, jobject, jint, jstring);

/*
 * Class:     com_cheuks_bin_anythingtest_jni_DllInterface
 * Method:    MoveWindow
 * Signature: (IIIIIZ)Z
 */
JNIEXPORT jboolean JNICALL Java_com_cheuks_bin_anythingtest_jni_DllInterface_MoveWindow
  (JNIEnv *, jobject, jint, jint, jint, jint, jint, jboolean);

#ifdef __cplusplus
}
#endif
#endif
